### ISSUE TITLE
 Error: Could not find MIME for Buffer <null>

### ISSUE THREAD

**Issue by sumanbgl** [udacity/cloud-developer#459]
utils.filterImageFromURL() is giving below error. How can this be resolved?

Error: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\@jimp\core\src\utils\image-bitmap.js:156:15)
    at Jimp.call [as parseBitmap] (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\@jimp\core\src\index.js:400:17)
    at parseBitmap (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\@jimp\core\src\index.js:344:14)
    at cb (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\@jimp\core\src\index.js:73:14)
    at cb (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\@jimp\core\src\request.js:47:9)
    at IncomingMessage.<anonymous> (C:\suman\udacity\scb\awsfs\cloud-developer\course-02\project\image-filter-starter-code\node_modules\phin\lib\phin.compiled.js:1:2038)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[ERROR] 16:41:19 Error: Could not find MIME for Buffer <null>

**Comment by abdelrazek-alaa** [comment]
I had the same issue yesterday while working on this project, and it turned out that the Wikipedia image link at the rubric wasn't supported by jimp. i tried another image link and it worked fine.
